name: Release
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:          
          PROJECT_FILE_PATH: FastExcel/FastExcel.csproj  
          NUGET_KEY: ${{secrets.NUGET_KEY}}
      - name: Create Release
        if: ${{ success() && steps.publish_nuget.outputs.VERSION != ''  && steps.publish_nuget.outputs.VERSION != null }}
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.publish_nuget.outputs.VERSION }}
          release_name: Release ${{ steps.publish_nuget.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: ${{ success() && steps.publish_nuget.outputs.VERSION != ''  && steps.publish_nuget.outputs.VERSION != null }}
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.publish_nuget.outputs.PACKAGE_PATH }}
          asset_name: ${{ steps.publish_nuget.outputs.PACKAGE_NAME }}
          asset_content_type: application/zip
